swagger: "2.0"
info:
  version: "2.0.3"
  title: iped-queue-events
# during dev, should point to your local machine
# host: localhost:8080
# basePath prefixes all resource paths
basePath: /v2
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/event-stream
paths:
  /events:
    x-swagger-router-controller: events
    get:
      description: List events by channel or evidence
      parameters:
        - name: channel
          in: query
          required: false
          type: string
        - name: evidence
          description: Evidence id
          in: query
          required: false
          type: string
        - name: since
          description: Since date-time
          in: query
          required: false
          type: string
          format: date-time
        - name: stream
          in: query
          required: false
          type: boolean
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/EventList"
        "404":
          description: Evidence not found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Adds an event
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Event"
      responses:
        "204":
          description: Success
        "404":
          description: Evidence not found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  EventList:
    type: array
    items:
      $ref: "#/definitions/Event"
  Event:
    required:
      - channel
      - type
    properties:
      channel:
        type: string
      type:
        type: string
      evidence:
        type: string
      date:
        type: string
        format: date-time
  ErrorResponse:
    required:
      - error
    properties:
      error:
        type: string
